apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: kapp-controller-test
spec:
  serviceAccountName: default
  fetch:
  - git:
      url: git@github.com:odinnordico/kapp-controller-private-test.git
      ref: origin/main
      secretRef:
        name: ssh-key-secret
      subPath: cm
  - git:
      url: git@github.com:odinnordico/kapp-controller-private-test.git
      ref: origin/main
      secretRef:
        name: ssh-key-secret
      subPath: secret
  template:
    - ytt: {}
  deploy:
  - kapp: {}
